#!/usr/bin/env python3
"""Render results.json (produced by meowdoku_z3.py) into CATALOGUE.md."""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
R = json.load(open(os.path.join(HERE, "results.json")))

out = []
w = out.append

w("# Meowdoku rule catalogue (auto-generated by `make_catalogue.py` from `results.json`)\n")
w("Legend for pictures: `#` cell of the region/box (may hold the cat), `x` provably empty, "
  "`.` no information, `A`/`B` cells of two regions.  Pictures show a 1-cell margin; "
  "row- or column-wide eliminations are listed as notes.\n")

# ---- capacities -----------------------------------------------------------
w("## Box capacity (max cats in an a x b rectangle)\n")
caps = R["box_capacity"]
sizes = sorted({int(k.split("x")[0]) for k in caps} | {int(k.split("x")[1]) for k in caps})
w("| a \\ b | " + " | ".join(str(b) for b in sizes) + " |")
w("|---|" + "---|" * len(sizes))
for a in sizes:
    row = []
    for b in sizes:
        k = f"{min(a,b)}x{max(a,b)}"
        row.append(str(caps.get(k, "")))
    w(f"| **{a}** | " + " | ".join(row) + " |")
w("")
w("Number of ways to fill an n x n box to capacity (Hertzsprung's problem, OEIS A002464 for n >= 4):\n")
w("| box | cats | patterns |\n|---|---|---|")
for k, v in R["full_patterns_square"].items():
    w(f"| {k} | {v['cats']} | {v['count']} |")
w("")

# ---- lower bound -----------------------------------------------------------
w("## Minimum cats in a corner box of an 8 x 8 board\n")
w("Formula `max(0, a+b-N, a-cap(a,N-b), b-cap(N-a,b))` exact on all boxes: "
  f"**{R['min_cats_formula_holds']}**\n")
lb = R["min_cats_in_box_N8"]
w("| a \\ b | " + " | ".join(str(b) for b in range(1, 9)) + " |")
w("|---|" + "---|" * 8)
for a in range(1, 9):
    w(f"| **{a}** | " + " | ".join(str(lb.get(f"{min(a,b)}x{max(a,b)}", "")) for b in range(1, 9)) + " |")
w("")

# ---- box rules ---------------------------------------------------------------
w("## k regions confined to an a x b box\n")
w("Proven on an at-most-one-per-row/column model (so independent of board size and "
  "position) and cross-checked against exactly-one models at N=10 (interior and corner) "
  "and N=12.\n")
for b in R["box_rules"]:
    if not b["forced_empty_local"] and not b["notes"]:
        continue
    checks = all([b["exact_N10_interior_same_local"], b["exact_N12_interior_same_local"],
                  b["exact_N10_corner_same_as_interior"]])
    w(f"### {b['box']} box, {b['k']} region(s) confined (capacity {b['capacity']})\n")
    w("```\n" + b["picture"] + "\n```")
    for n in b["notes"]:
        w(f"- {n}")
    if not checks:
        w(f"- WARNING: exact-model cross-check differed: {b}")
    w("")

# ---- shapes -----------------------------------------------------------------
w("## A single region of a given shape (free polyominoes up to size 5)\n")
w(f"Every one of these equals the intersection rule exactly: "
  f"**{R['shape_rules_all_equal_intersection_rule']}** (so nothing beyond the "
  "intersection rule can be squeezed out of one region on its own).\n")
for s in R["shape_rules"]:
    w(f"### size {s['size']}: cells {s['cells']}\n")
    w("```\n" + s["picture"] + "\n```")
    rows = {r for r, _ in s["cells"]}
    cols = {c for _, c in s["cells"]}
    if len(rows) == 1:
        w("- the whole row is empty outside the region")
    if len(cols) == 1:
        w("- the whole column is empty outside the region")
    w("")

# ---- symbolic proofs ----------------------------------------------------------
w("## Rules proven with a fully symbolic region map\n")
for N in (5, 6):
    key = f"symbolic_proofs_N{N}"
    if key in R:
        w(f"### N = {N}\n")
        w("| claim | proven |\n|---|---|")
        for k, v in R[key].items():
            w(f"| `{k}` | {v} |")
        w("")

# ---- pairs ------------------------------------------------------------------
ps = R["pair_search"]
w("## Two regions inside a 3 x 3 window\n")
w(f"{ps['pairs_examined_up_to_symmetry']} pairs of connected shapes (size <= 4, disjoint, "
  f"up to the 8 symmetries) were examined.  {len(ps['impossible'])} pairs are impossible "
  f"(a valid puzzle never contains them).  {len(ps['novel'])} pairs yield eliminations that "
  "the direct rules (intersection, row/column counting, box rules) miss; in every one of them "
  f"the missing cells follow from ONE what-if step (pairs needing more: "
  f"{ps['pairs_beyond_one_step_lookahead']}).\n")
w("### Impossible pairs\n")
for f in ps["impossible"]:
    w(f"- A = {f['S1']}, B = {f['S2']}")
w("")
w("### Pairs with a one-step what-if elimination\n")
w("`x` marks every cell forced empty (direct rules included); the cells that need the "
  "what-if are listed under each picture.\n")
for i, f in enumerate(ps["novel"], 1):
    w(f"#### Pair {i}: A = {f['S1']}, B = {f['S2']}\n")
    w("```\n" + f["picture"] + "\n```")
    w(f"- what-if eliminations: {f['novel']}\n")

with open(os.path.join(HERE, "CATALOGUE.md"), "w") as fh:
    fh.write("\n".join(out) + "\n")
print("wrote CATALOGUE.md")
