#!/usr/bin/env python3
"""Translate the walkthrough of the hardest 10x10 into Lean moves (lean/Meowdoku/Game10.lean).

Every solver log entry maps to one engine move:
  single                    -> Move.placeCat <unit>
  common attack             -> Move.commonAttack <unit>
  colours locked in lines   -> Move.hallK (line coord) (colourC) lines... colours...
  lines made of few colours -> Move.hallK (colourC) (line coord) colours... lines...
  what-if                   -> Move.whatIf cell [inner moves]
"""
import json
import os
import re

from walkthrough import human_solve

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "lean", "Meowdoku", "Game10.lean")
NAMES = ["purple", "yellow", "pink", "brown", "orange", "green", "dark green", "blue", "rose", "gold"]


def unit(kind, idx):
    return {"row": f"(row {idx})", "col": f"(column {idx})", "colour": f"(colour {idx})"}[kind]


def entry_to_move(e):
    rule, what = e["rule"], e["what"]
    if rule == "single":
        kind, idx = what.split()[0], int(what.split()[1])
        return f"Move.placeCat {unit(kind, idx)}", f"{kind} {idx + 1 if kind != 'colour' else NAMES[idx]} has one cell left"
    if rule == "common attack":
        kind, idx = what.split()[4], int(what.split()[5])
        return f"Move.commonAttack {unit(kind, idx)}", f"common attack from {kind + ' ' + str(idx + 1) if kind != 'colour' else NAMES[idx]}"
    if rule == "colours locked in lines":
        cols = [int(x) for x in re.findall(r"\d+", what.split("fit")[0])]
        lines = [int(x) for x in re.findall(r"\d+", what.split("inside")[1])]
        F = "(rowC B10)" if "rows" in what else "(colC B10)"
        k = len(cols)
        args = " ".join(str(v) for v in lines) + " " + " ".join(str(v) for v in cols)
        return (f"Move.hall{k} {F} (colourC B10) {args}",
                f"{' and '.join(NAMES[g] for g in cols)} fit inside {'rows' if 'rows' in what else 'columns'} "
                f"{' and '.join(str(v + 1) for v in lines)}")
    if rule == "lines made of few colours":
        lines = [int(x) for x in re.findall(r"\d+", what.split("contain")[0])]
        cols = [int(x) for x in re.findall(r"\d+", what.split("colours")[-1])]
        E = "(rowC B10)" if what.startswith("rows") else "(colC B10)"
        k = len(cols)
        args = " ".join(str(v) for v in cols) + " " + " ".join(str(v) for v in lines)
        return (f"Move.hall{k} (colourC B10) {E} {args}",
                f"{'rows' if what.startswith('rows') else 'columns'} {' and '.join(str(v + 1) for v in lines)} "
                f"contain only {' and '.join(NAMES[g] for g in cols)}")
    raise ValueError(rule)


def main():
    H = json.load(open(os.path.join(HERE, "hardest.json")))
    grid = H["10"]["hardest"][0]["grid"]
    _, phases, _ = human_solve(grid)
    lines = []
    for ph in phases:
        lines.append(f"    -- {ph['title']}")
        if ph["kind"] == "whatif":
            inner = [entry_to_move(e) for e in ph["raw_trace"]]
            r, c = ph["cell"]
            lines.append(f"    Move.whatIf (cell {r} {c}) [   -- suppose a cat on r{r + 1}c{c + 1} ...")
            for m, why in inner:
                lines.append(f"      {m},   -- {why}")
            lines.append("      ],   -- ... and some unit has no cell left: r%dc%d is empty" % (r + 1, c + 1))
        else:
            for e in ph["raw"]:
                m, why = entry_to_move(e)
                lines.append(f"    {m},   -- {why}")
    moves = "\n".join(lines).rstrip(",") if False else "\n".join(lines)
    # strip the trailing comma of the last move
    idx = moves.rfind(",   --")
    moves = moves[:idx] + moves[idx + 1:]
    src = f'''import Meowdoku.Boards

/-!
# Playing the hardest 10 × 10 through the proof assistant

`game` is the walkthrough of `WALKTHROUGH.md`, one engine move per step
(generated by `make_lean_game.py`).  Lean evaluates the moves; the final
theorems are checked by `decide +kernel`, so the whole solve is verified by
Lean's kernel with no extra axioms.

To play yourself: edit `game`, run `#eval IO.println (play game (Cand.all 10)).show`
to see the board, and try to reach a state where `hardest10_unique` type-checks.
-/

namespace Meowdoku

abbrev B10 := hardest10
abbrev colour (g : Nat) : Unit B10 := colourU B10 ⟨g % 10, Nat.mod_lt _ (by decide)⟩
abbrev row (r : Nat) : Unit B10 := rowU B10 ⟨r % 10, Nat.mod_lt _ (by decide)⟩
abbrev column (c : Nat) : Unit B10 := colU B10 ⟨c % 10, Nat.mod_lt _ (by decide)⟩
abbrev cell (r c : Nat) : Cell 10 := (⟨r % 10, Nat.mod_lt _ (by decide)⟩, ⟨c % 10, Nat.mod_lt _ (by decide)⟩)

/-- The full solve (rows, columns and colours are 0-indexed here; comments use 1-indexed names). -/
def game : List (Move B10) :=
  [
{moves}
  ]

/-- The state after the game. -/
def final : Cand 10 := play game (Cand.all 10)

#eval IO.println final.show

/-- Every solution of the board is `sol10`. -/
theorem hardest10_unique : ∀ s : Solution hardest10, s.col = sol10 :=
  unique_of_play game sol10 (by decide +kernel)

/-- `sol10` really is a solution. -/
def hardest10_solution : Solution hardest10 where
  col := sol10
  col_inj := by decide +kernel
  col_all := by decide +kernel
  colour_inj := by decide +kernel
  colour_all := by decide +kernel
  noTouch := by decide +kernel

/-- So the board has exactly one solution. -/
theorem hardest10_exists_unique : ∃ s : Solution hardest10, ∀ t : Solution hardest10, t.col = s.col :=
  ⟨hardest10_solution, fun t => hardest10_unique t⟩

end Meowdoku
'''
    with open(OUT, "w") as f:
        f.write(src)
    print(f"wrote {OUT} with {sum(1 for l in lines if l.strip().startswith('Move.'))} moves")


if __name__ == "__main__":
    main()
