#!/usr/bin/env python3
"""Uniqueness certificates for every level of pack3d.json -> PACK3D_PROOFS.md.

Three independent checks per level:
  1. Z3 enumerates all solutions of the level (must find exactly one, equal to the stored one).
  2. The generator's backtracking count (how the level was selected).
  3. A human-readable derivation: the direct rules of the rulebook (each proven sound) applied
     until every cat is forced.  For 3x3x3 levels the exhaustive 8-placement table is given instead.
"""
import itertools, json, os
from z3 import And, Bool, Not, Or, PbEq, Solver, sat
import nd

HERE = os.path.dirname(os.path.abspath(__file__))
pack = json.load(open(os.path.join(HERE, "pack3d.json")))
NAMES = ["purple", "yellow", "pink", "brown", "orange", "green", "dark green", "blue", "rose", "gold"]


def cname(c):
    return f"L{c[0]+1}r{c[1]+1}c{c[2]+1}"


def z3_solutions(L, limit=3):
    n = L["n"]; cells = list(itertools.product(range(n), repeat=3))
    col = {c: L["colour"][c[0]*n*n + c[1]*n + c[2]] for c in cells}
    s = Solver(); X = {c: Bool(str(c)) for c in cells}
    for a in range(3):
        for v in range(n):
            s.add(PbEq([(X[c], 1) for c in cells if c[a] == v], 1))
    for g in range(n):
        s.add(PbEq([(X[c], 1) for c in cells if col[c] == g], 1))
    for p, q in itertools.combinations(cells, 2):
        if nd.touch(p, q):
            s.add(Not(And(X[p], X[q])))
    sols = []
    while s.check() == sat and len(sols) < limit:
        m = s.model(); sol = sorted(c for c in cells if m.eval(X[c], True)); sols.append(sol)
        s.add(Or([Not(X[c]) for c in sol]))
    return sols


def describe(e, n):
    axisname = {"axis0": "layer", "axis1": "row", "axis2": "column"}
    rule, what, removed, placed = e["rule"], e["what"], e["removed"], e["placed"]
    def unit(w):
        kind, idx = w.split()[0], int(w.split()[1])
        return NAMES[idx] if kind == "colour" else f"{axisname[kind]} {idx+1}"
    if rule == "single":
        return f"**{unit(what).capitalize()} has one cell left**: cat on {cname(placed)}; it crosses out {len(removed)} cells."
    if rule == "common attack":
        return f"**Common attack from {unit(what)}**: every remaining cell of it attacks {', '.join(cname(c) for c in removed[:8])}{' ...' if len(removed) > 8 else ''} ({len(removed)} cells crossed out)."
    return f"**{rule.capitalize()}** ({what}): {len(removed)} cells crossed out."


out = ["# Uniqueness certificates for the Meowdoku Cube levels\n",
       "Every level of `pack3d.json` is checked three ways (generated by `make_pack3d_proofs.py`):\n",
       "1. **Z3** enumerates all solutions of the level's constraints (one cat per layer in each direction, "
       "one per colour, no touching); it must find exactly one, and it must be the stored solution.",
       "2. **Backtracking** in `nd.py` (independent code) counted the solutions when the level was generated.",
       "3. **A derivation**: for 3×3×3 levels, the complete list of the 8 possible three-cat placements with "
       "their colours; for larger levels, the chain of direct rules (single candidate, common attack, "
       "colours locked in slices, slices made of few colours) that forces every cat.  Each rule is proven "
       "sound in `RULES.md` / `lean/`, and the argument only uses separating maps and touching, so it holds "
       "unchanged in 3D.  A derivation that reaches all n cats *is* a uniqueness proof: any solution must "
       "agree with every forced step.\n",
       "Cells are written L‹layer›r‹row›c‹column›, counted from 1.\n"]
summary = []
for L in pack:
    n = L["n"]
    sols = z3_solutions(L)
    stored = sorted(tuple(c) for c in L["solution"])
    z3ok = len(sols) == 1 and sols[0] == stored
    cells = list(itertools.product(range(n), repeat=3))
    colour = {c: L["colour"][c[0]*n*n + c[1]*n + c[2]] for c in cells}
    p = nd.PuzzleND(n, 3, colour)
    bt = len(p.count_solutions(limit=3))
    st = nd.StateND(p, log=[])
    st.propagate()
    derived = st.solved()
    summary.append((L["id"], z3ok, bt, derived, len(st.log)))
    out.append(f"## Level {L['id']} ({n}×{n}×{n})\n")
    out.append(f"* Z3: {'exactly one solution, equal to the stored one' if z3ok else 'MISMATCH'}")
    out.append(f"* backtracking count: {bt}")
    out.append(f"* stored solution: {', '.join(cname(c) for c in stored)}\n")
    if n == 3:
        out.append("Exhaustive check.  A 3×3×3 admits exactly 8 placements of three mutually non-attacking cats "
                   "(one per layer, row and column, none touching).  Their colours:\n")
        out.append("| placement | colours | valid? |\n|---|---|---|")
        for combo in itertools.combinations(cells, 3):
            if all(not nd.attack_slice(a, b) for a, b in itertools.combinations(combo, 2)):
                cols = [NAMES[colour[c]] for c in combo]
                ok = len(set(cols)) == 3
                out.append(f"| {', '.join(cname(c) for c in combo)} | {', '.join(cols)} | {'**yes**' if ok else 'no'} |")
        out.append("")
    else:
        out.append(f"Derivation by the direct rules ({len(st.log)} steps, {'reaches all cats' if derived else 'INCOMPLETE'}):\n")
        for i, e in enumerate(st.log, 1):
            out.append(f"{i}. {describe(e, n)}")
        out.append("")
out.insert(1, "| level | size | Z3 unique | backtracking count | derivation complete | steps |\n|---|---|---|---|---|---|\n" +
           "\n".join(f"| {i} | {i.split('-')[0]}³ | {'yes' if z else 'NO'} | {b} | {'yes' if d else 'NO'} | {k} |" for i, z, b, d, k in summary) + "\n")
open(os.path.join(HERE, "PACK3D_PROOFS.md"), "w").write("\n".join(out) + "\n")
print("all Z3 unique:", all(z for _, z, _, _, _ in summary), "| all derivations complete:", all(d for _, _, _, d, _ in summary))
