import Meowdoku.Boards

/-!
# Playing the hardest 10 × 10 through the proof assistant

`game` is the walkthrough of `WALKTHROUGH.md`, one engine move per step
(generated by `make_lean_game.py`).  Lean evaluates the moves; the final
theorems are checked by `decide +kernel`, so the whole solve is verified by
Lean's kernel with no extra axioms.

To play yourself: edit `game`, run `#eval IO.println (play game (Cand.all 10)).show`
to see the board, and try to reach a state where `hardest10_unique` type-checks.
-/

namespace Meowdoku

abbrev B10 := hardest10
abbrev colour (g : Nat) : Unit B10 := colourU B10 ⟨g % 10, Nat.mod_lt _ (by decide)⟩
abbrev row (r : Nat) : Unit B10 := rowU B10 ⟨r % 10, Nat.mod_lt _ (by decide)⟩
abbrev column (c : Nat) : Unit B10 := colU B10 ⟨c % 10, Nat.mod_lt _ (by decide)⟩
abbrev cell (r c : Nat) : Cell 10 := (⟨r % 10, Nat.mod_lt _ (by decide)⟩, ⟨c % 10, Nat.mod_lt _ (by decide)⟩)

/-- The full solve (rows, columns and colours are 0-indexed here; comments use 1-indexed names). -/
def game : List (Move B10) :=
  [
    -- Cat 1: r9c8
    Move.commonAttack (colour 0),   -- common attack from purple
    Move.commonAttack (colour 2),   -- common attack from pink
    Move.commonAttack (colour 3),   -- common attack from brown
    Move.commonAttack (colour 6),   -- common attack from dark green
    Move.commonAttack (colour 7),   -- common attack from blue
    Move.placeCat (colour 8),   -- colour rose has one cell left
    -- Direct rules
    Move.commonAttack (colour 6),   -- common attack from dark green
    Move.commonAttack (colour 7),   -- common attack from blue
    Move.commonAttack (colour 2),   -- common attack from pink
    Move.hall2 (colC B10) (colourC B10) 1 2 2 7,   -- pink and blue fit inside columns 2 and 3
    -- Stuck: try r6c1
    Move.whatIf (cell 5 0) [   -- suppose a cat on r6c1 ...
      Move.commonAttack (colour 2),   -- common attack from pink
      Move.commonAttack (colour 3),   -- common attack from brown
      Move.commonAttack (colour 4),   -- common attack from orange
      ],   -- ... and some unit has no cell left: r6c1 is empty
    -- Cat 2: r7c1
    Move.placeCat (column 0),   -- col 1 has one cell left
    -- Cat 3: r8c3
    Move.placeCat (colour 7),   -- colour blue has one cell left
    -- Cat 4: r4c7
    Move.hall2 (colC B10) (colourC B10) 8 9 0 9,   -- purple and gold fit inside columns 9 and 10
    Move.hall3 (colC B10) (colourC B10) 6 8 9 0 3 9,   -- purple and brown and gold fit inside columns 7 and 9 and 10
    Move.commonAttack (column 6),   -- common attack from col 7
    Move.commonAttack (colour 5),   -- common attack from green
    Move.hall3 (rowC B10) (colourC B10) 2 4 5 2 4 5,   -- pink and orange and green fit inside rows 3 and 5 and 6
    Move.hall2 (colourC B10) (rowC B10) 0 1 0 1,   -- rows 1 and 2 contain only purple and yellow
    Move.hall3 (colourC B10) (rowC B10) 0 1 9 0 1 9,   -- rows 1 and 2 and 10 contain only purple and yellow and gold
    Move.hall1 (colC B10) (colourC B10) 9 9,   -- gold fit inside columns 10
    Move.commonAttack (row 1),   -- common attack from row 2
    Move.placeCat (row 3),   -- row 4 has one cell left
    -- Cat 5: r10c10
    Move.commonAttack (row 5),   -- common attack from row 6
    Move.placeCat (row 9),   -- row 10 has one cell left
    -- Cat 6: r1c9
    Move.placeCat (column 8),   -- col 9 has one cell left
    -- Cat 7: r6c6
    Move.placeCat (colour 5),   -- colour green has one cell left
    -- Cat 8: r3c2
    Move.placeCat (row 2),   -- row 3 has one cell left
    -- Cat 9: r5c4
    Move.placeCat (row 4),   -- row 5 has one cell left
    -- Cat 10: r2c5
    Move.placeCat (column 4)   -- col 5 has one cell left
  ]

/-- The state after the game. -/
def final : Cand 10 := play game (Cand.all 10)

#eval IO.println final.show

/-- Every solution of the board is `sol10`. -/
theorem hardest10_unique : ∀ s : Solution hardest10, s.col = sol10 :=
  unique_of_play game sol10 (by decide +kernel)

/-- `sol10` really is a solution. -/
def hardest10_solution : Solution hardest10 where
  col := sol10
  col_inj := by decide +kernel
  col_all := by decide +kernel
  colour_inj := by decide +kernel
  colour_all := by decide +kernel
  noTouch := by decide +kernel

/-- So the board has exactly one solution. -/
theorem hardest10_exists_unique : ∃ s : Solution hardest10, ∀ t : Solution hardest10, t.col = s.col :=
  ⟨hardest10_solution, fun t => hardest10_unique t⟩

end Meowdoku

#print axioms Meowdoku.hardest10_unique
#print axioms Meowdoku.hardest10_exists_unique
